# ansible/files/docker-compose.yml   (or keep your current file on the server and just add the volume)
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /opt/apps/www:/usr/share/nginx/html:ro   # <-- serve our radio page
  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /opt/apps/gatus-config.yaml:/config/config.yaml:ro