services:
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - "8080:8080"
    volumes:
      - ./gatus-config.yaml:/config/config.yaml:ro   # <— make sure this path matches
    environment:
      - GATUS_CONFIG_PATH=/config/config.yaml        # <— forces the path Gatus reads
    restart: unless-stopped